---
functions:
  updateThingToDo:
    runtime: nodejs12.x
    name: ${self:provider.stage}-lambda-update-thing-todo
    handler: updateThingToDo/index.handler
    description: Updates a thing todo
    memorySize: 192 # optional, in MB, default is 1024
    timeout: 10 # optional, default is 6
    environment:
      DYNAMODB_REGION: ${self:provider.region}
      DYNAMODB_ONE_TABLE: ${self:custom.oneTableName}
      ASSETS_BUCKET_URI: "https://${ssm:/${self:provider.stage}/route53/assets/name}"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${self:custom.awsAccountId}:table/${self:custom.oneTableName}"
