---
functions:
  thingsToDoByIds:
    runtime: nodejs12.x
    name: ${self:provider.stage}-lambda-things-todo-by-ids
    handler: thingsToDoByIds/index.handler
    description: Batch things todo byid
    memorySize: 128 # optional, in MB, default is 1024
    timeout: 10 # optional, default is 6
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchGetItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:${self:custom.awsAccountId}:table/${self:custom.oneTableName}"
    environment:
      DYNAMODB_REGION: ${self:provider.region}
      DYNAMODB_ONE_TABLE: ${self:custom.oneTableName}

