---
functions:
  newVersion:
    runtime: nodejs12.x
    name: ${self:provider.stage}-lambda-new-version
    handler: newVersion/index.handler
    description: New version of a thing todo
    memorySize: 192 # optional, in MB, default is 1024
    timeout: 10 # optional, default is 6
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${self:custom.awsAccountId}:table/${self:custom.oneTableName}"    
    environment:
      DYNAMODB_REGION: ${self:provider.region}
      DYNAMODB_ONE_TABLE: ${self:custom.oneTableName}
