---
service: hopnamiasto-audit-service

frameworkVersion: ">=1.21.0 <2.0.0"

plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
  - serverless-bundle
provider:
  name: aws
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  region: eu-central-1
  runtime: nodejs12.x
  environment: 
    LOG_LEVEL: ${self:custom.logLevel.${self:provider.stage}}
    
package:
  individually: true
  exclude:
    - "**/**"
  include:
    - "lib"

custom:
  awsAccountId: "#{AWS::AccountId}"
  oneTableName: ${self:provider.stage}-one-table
  logLevel:
    dev: DEBUG
    test: DEBUG
    prod: INFO  

functions:
  - ${file(./approveThingToDo/serverless.yml):functions}
  - ${file(./rejectThingToDo/serverless.yml):functions}


