---
functions:
  addToMyFavorites:
    runtime: nodejs12.x
    name: ${self:provider.stage}-lambda-add-to-my-favorites
    handler: addToMyFavorites/index.handler
    description: Adds to my favories
    memorySize: 128 # optional, in MB, default is 1024
    timeout: 10 # optional, default is 6
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${self:custom.awsAccountId}:table/${self:custom.oneTableName}"    
    environment:
      DYNAMODB_REGION: ${self:provider.region}
      DYNAMODB_ONE_TABLE: ${self:custom.oneTableName}