version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd services/booking 
      - bash ./build.sh install
  build:
    commands:
      - bash ./build.sh deploy $STAGE $REGION