---
functions:
  initProfile:
    runtime: nodejs12.x
    name: ${self:provider.stage}-lambda-init-profile
    handler: initProfile/index.handler
    description: initializes user/organiser profile on signup
    memorySize: 128 # optional, in MB, default is 1024
    timeout: 10 # optional, default is 6
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 
          - "arn:aws:dynamodb:${self:provider.region}:${self:custom.awsAccountId}:table/${self:custom.oneTableName}"
    environment:
      DYNAMODB_REGION: ${self:provider.region}
      DYNAMODB_ONE_TABLE: ${self:custom.oneTableName}
