---
resources:
  Resources:
    AppSyncESOrganiserServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: ${self:provider.stage}-appsync-organiser-elasticsearch-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Principal:
              Service:
              - "appsync.amazonaws.com"
            Action:
            - "sts:AssumeRole"
        Policies:
        - PolicyName: elasticsearch-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: "Allow"
              Action:
              - "es:*"
              Resource:
              - 'Fn::Join':
                - ''
                - - 'arn:aws:es:'
                  - Ref: 'AWS::Region'
                  - ':'
                  - Ref: 'AWS::AccountId'
                  - ':domain/'
                  - "${self:custom.esDomainName}"
                  - '/*'
