const DRAFT = 'DRAFT';
const PENDING = 'PENDING';
const PUBLISHED = 'PUBLISHED';
const REJECTED = 'REJECTED';
const DELETED = 'DELETED';

export {
    DRAFT,
    PENDING,
    PUBLISHED,
    REJECTED,
    DELETED
};